### ISSUE TITLE
[Feature Request] Styling the search results

### ISSUE THREAD

**Issue by rahuls** [bnason-nf/findallinfile#12]
Hello, 

First of all, thank you @bnason-nf for making this extension. This tool literally saves me around 1 hour of my time daily. In return I sleep early and get some good rest😁

Earlier I have used Notepad++, the find function automatically highlights the searched text as in the below picture

![image](https://user-images.githubusercontent.com/7702470/118917827-52f0cd80-b94f-11eb-9271-7f52fc64e163.png)

Is there any way to style the search results? 

I work with large files where I need to navigate around 1000+ search results. Without any highlights its difficult to go through these results. 

Hope you make a solution for this problem.

Thanks
Rahul

**Comment by bnason-nf** [comment]
Hi @rahuls,

I added this feature in version v1.1.4 today, please let me know what you think.

Thanks,
Benbuck

**Comment by rahuls** [comment]
Hi Benbuck,

Thanks for your quick solution. Its working well and good. 

![image](https://user-images.githubusercontent.com/7702470/119090713-94ee4200-ba29-11eb-9f91-8bc20defa6cf.png)

Regards, 
Rahul
