### ISSUE TITLE
Result lines are badly trimmed

### ISSUE THREAD

**Issue by manmilani** [bnason-nf/findallinfile#18]
Hi bnason-nf,

Thank you for this extension! It is the only one I could find to provide this simple but crucial functionality and I have already found it to be very useful.

**Problem:**
However, a problem I found is how it trims the found result lines. One main use case for this extension (at least for me) is to get a list of result lines that I can just look at in one place, without having to inspect (hover over) each line manually again. For example, in the screenshot below you can see that the results are trimmed, even though there is all that empty space left in the widget.
![FindInAllFiles_Screenshot](https://user-images.githubusercontent.com/87471487/177684668-0dd90d27-cfe7-4b58-81db-8d4dd27eeca3.png)

**Desired Behaviour:**
My desired behaviour would be for the results list to simply just print every line as it is, without trimming anything, perhaps with a horizontal scroll bar appearing if the lines are wider than the width of the widget. Additionally, it would also be good for each result line in the list to be prefixed with the line number within the file.

**Can I help?**
If you agree with the desired behaviour above, let me know if you think you will not find the time to make those changes in your code any time soon, and if you would like me to have a crack at it.

Thanks.

**Comment by manmilani** [comment]
I just spent a few minutes looking at the code, and I guess one quick solution could be to make "FindResult.truncateContext" configurable via Extension settings, with an option to disable it (e.g. quick&dirty value -1).

**Comment by bnason-nf** [comment]
Hi @manmilani,

There is a feature that allows you to click on the first or last lines of the results (the line that says "Searching for..." or the line that says "Found..."). When you do this, the entire contents of the search results are copied to the clipboard, untrimmed. Would that help your needs?

Thanks,
Benbuck

**Comment by bnason-nf** [comment]
Hi @manmilani,

Related to my last comment, I was realizing it might be possible for me to open a new editor tab with the search result contents instead of (or in addition to) copying it to the clipboard.

Also, I want to make sure you are aware that VSCode added a button to the built-in Search pane to "Search only in Open Editors", which is pretty much identical in functionality to this extension if you only have one editor tab open.

To be clear, having a configurable formatting option to allow you to avoid trimming the results is also possible, I'm just exploring possible solutions.

Thanks,
Benbuck

**Comment by manmilani** [comment]
Hi @bnason-nf,

Thanks for getting back to me, and for your comments/suggestions.

I am going to respond to your comments first, and then go on an elaborate my reasons and use case afterwards.

**My Response to your comments:**
[1] Yes, I was aware of the existing VScode feature to search only in the currently open tabs, but I don't really find it that useful if I'm honest and rarely find myself using it.
[2] Yes, I was aware of the feature in your extension that copies search results to clipboard. This is certainly a good feature, but still not easy enough for my usage.
[3] Your suggestion to "_open a new editor with the search results, upon click on the first or last line_" is definitely one step closer to a more user-friendly solution. However, that means that we would end up with multiple editors open upon multiple searches, closing each of which would still take some time.

**My Use Case:**
I decided to describe some of my use-cases for you, to make it easier to understand each other. I often deal with very large code-bases with thousands of files, on a remote server, and also deal with looking through and comparing many system log files. In doing that, I often need to search for terms not only in the whole workspace (Ctrl+Shift+F) to find words in the code and have those files open, but then at the same time I also need to look for certain words in log files (usually one at a time). 

When searching for terms in log files:
- I would rather _not_ find results from the source code I already have open (i.e. [1] above: existing open tabs)
- I usually care about the whole line, especially the leading timestamps i.e. (i.e. no trimming), to compare with timestamps of similar events in other log files that I also have open.
- I do searches of different terms multiple times in a row, consecutively and quickly (i.e. [2] above: copy to clipboard and look at it elsewhere). 
- In doing all this, I usually already have my VScode editor split in (at least) 2 parts, and opening another editor just ends up either taking up more space or masking a file I am already looking at (i.e. [3] above, opening an editor). 

So I quite like that your extension has its own separate widget to show the results, that can just be chucked in the lower pane, not interfering with the rest of the window (widgets, contents and editors).

**My Opinion:**
- I understand that perhaps my use case, in the way that I described it, may seem too specific, but I do think that most developers would have at least some of those use-cases and problems, and would benefit from a solution that would address all that.
- Conceptually thinking, I find it hard to justify why the search results should be trimmed at all, especially when there is space available in the widget to show the full line (or as much of it as possible). I understand that was probably a mechanism to highlight the occurrence of the searched term within the line, but perhaps a better way would be to actually highlight the occurrence within the result line, in some future time (as a new feature).

**My Conclusion:**
I guess what I'm after is the "Find All In Current File" functionality of Notepad++ (hoping you are familiar with it). I find that to be a very good design.

Sorry if I wrote too much, and thank you again for this awesome extension.

Cheers,
Mani

**Comment by bnason-nf** [comment]
Hi @manmilani,

Thanks for the detailed response and all the context. Let me think about this and get back to you.

In the mean time, if you're willing to experiment, would you mind please changing the `FindResult.truncateContext = 15` to other values and see if it works for you? You can find that line at the bottom of `VSCode/data/extensions/bnason-nf.findallinfile-1.1.6/out/findResult.js`.

Thanks,
Benbuck

**Comment by manmilani** [comment]
Thanks for the hint! I did make the change (and also added line numbers) in that file and it is working perfectly for me now! I will do some more experiments in the next few days and send you a pull-request, just for you try if you feel like it.

**Comment by bnason-nf** [comment]
Hi @manmilani,

I added the option you requested and released version 1.2.0 with that change. Please let me know if it works for you.

Thanks,
Benbuck
