### ISSUE TITLE
[feature request] show line numbers in search results 

### ISSUE THREAD

**Issue by gthbusr0** [bnason-nf/findallinfile#23]
thank you for this extension that I heavily use.

Wondering if line numbers can also be included in search results so that when browsing them we have the ability to skip over to desired collocated code blocks bypassing few of them. for eg. if we eyeball first instance at line 10 and would like to ignore surrounding code block as it isn't applicable, we'd like to move on to the next nearby code block starting line 20 etc. (guestimated by line number).

**Comment by bnason-nf** [comment]
Hi @gthbusr0,

Line numbers are already available in two ways:

1. If you hover your mouse over one of the find result items, it should show a popup box with more information about that item, including the line and column numbers.
2. If you click the first ("Searching for...") or last ("Found n occurrences") lines of the results, it will copy the full results into your clipboard. The contents of that will include the line and column numbers.

Does that help?

-Benbuck

**Comment by bnason-nf** [comment]
Hi @gthbusr0,

I'm going to close this out under the assumption that the existing line number information is sufficient.

-Benbuck

**Comment by gthbusr0** [comment]
@bnason-nf  sorry for the late reply. i didn't know this exists. if possible it really helps to have the line number displayed directly like Notepad++ instead of viewing by hovering.

**Comment by gthbusr0** [comment]
Only updating for the benefit of others like me looking for this functionality. I got this functionality via the other extension I use: https://github.com/shibayu36/vscode-search-in-current-file/issues/16
