### ISSUE TITLE
Add index to find results

### ISSUE THREAD

**Issue by sourabh2902** [bnason-nf/findallinfile#3]
Hi @bnason-nf  
Thanks for this extension! This is very helpful. 
Can you kindly consider adding the following enhancement to the extension? 
Today when we use the extension the results are shown in the following way : 
Searching for regex "my_name"" in "my_name.txt" 
4:33	         my_name
91:33	 my_name
178:33	 my_name
265:33	 my_name

 can we enhance this to the following snippet ? 
![image](https://user-images.githubusercontent.com/2882728/83981382-1f4d9c80-a8d2-11ea-89db-63aa820bbc0b.png)
Please note that in the snippet, how the first column shows the match count. The rest is as before. 

Benefit of the enhancement: 
Suppose if a user is searching in a huge file, and wants to navigate to specific match count, then today we will need to copy the search results to the clipboard, identify the <linenumber:column> pair and then jump to the context, with this enhancement process will become much faster. 

Thanks!

**Comment by bnason-nf** [comment]
Hi @sourabh2902,

Thanks for the feedback. If i'm understanding correctly, you would like me to add an index to each match, basically like a line number for the match result list? I can easily do that, but there are two things that are unclear to me:

1. I don't know of a good way to format it nicely in columns like the image you provided, I don't think the VSCode APIs allow that (but if they do I'd be very happy if someone could let me know how). Would it still be useful if the formatting were not in nice columns?

2. Based on your use case of jumping to the result, this change should be unnecessary. If you have the latest version of the extension, you can just click on the individual result you are interested in and you should automatically jump to that location in your file. Is this not working for you?

Thanks,
Benbuck

**Comment by bnason-nf** [comment]
Hi @sourabh2902,

I was just re-reading your request, and think I may understand a little better now. It sounds like your use case is that you would like to specifically jump to (for example) match number 12345. I hadn't considered that, and I understand how awkward it would be to do that currently. 

If this understanding is correct, please ignore my second concern above, but I would still like to hear your thoughts on the formatting issue.

Thanks,
Benbuck

**Comment by sourabh2902** [comment]
Hi @bnason-nf 

For item 1 - For now, even if we don't have nice formatted columns it should be fine, I will search on the google and see if I can find anything and let you know (I am very new at extension development, so I will take some time) I will update you as soon as I find something.  

For item 2 - your understanding is absolutely correct :). Today we don't have a good way to jump to match number 12345 directly.

**Comment by bnason-nf** [comment]
Hi @sourabh2902,

I just updated the extension with this feature. Please let me know how it works for you.

Thanks,
Benbuck

**Comment by sourabh2902** [comment]
Thanks @bnason-nf  Let me install the new version and update you back
