### ISSUE TITLE
[enhancement] Copy selected text to Search String box

### ISSUE THREAD

**Issue by SAbboushi** [bnason-nf/findallinfile#5]
Great extension!  Would like if the selected text in editor is used to fill the search string box when I use the Editor Context Menu commands

**Comment by bnason-nf** [comment]
Hi @SAbboushi,

I like this suggestion, I will see if I can get it to work. To me it makes the most sense for normal string searches, not for regular expressions. What do you think?

Thanks,
Benbuck

**Comment by SAbboushi** [comment]
> To me it makes the most sense for normal string searches

I agree that most times, it will be for normal string searches -- but, I was using regex when I realized I would benefit from such a feature i.e. I hope you'll consider it for regex too.  If in the implementation you can leave the text selected in the search string box so that typing replaces the text automatically (instead of the user having to type e.g. CTRL/A to select), then I suggest there's no/little downside for implementing the feature for all types of searches

**Comment by bnason-nf** [comment]
Hi @SAbboushi,

Thanks for the feedback. I've implemented it as you suggested. I am trying to fix an unrelated bug I just noticed, but after that I should be able to push out a new release.

Benbuck

**Comment by SAbboushi** [comment]
Great and Thanks!

**Comment by bnason-nf** [comment]
Hi @SAbboushi,

I just released version 0.,9.0, please let me know how this works for you.

Thanks,
Benbuck

**Comment by SAbboushi** [comment]
Perfect!
