### ISSUE TITLE
[bug] ironically, 0.9.1 broke activity bar icon...

### ISSUE THREAD

**Issue by SAbboushi** [bnason-nf/findallinfile#7]
there is still a square area in the activity bar for the extension, but the square is  empty and not even visible unless hovering over that area

**Comment by bnason-nf** [comment]
Hi @SAbboushi,

That's very strange, for me the activity bar icon is there, but the icon for the extension itself is missing inside the marketplace, both within VSCode and through the normal web site. Thanks for reporting this, I will investigate.

Benbuck

**Comment by bnason-nf** [comment]
Hi @SAbboushi,

I just fixed the icon problem I was seeing, but I'm not sure if it's the same one you were seeing. Could you please try release 0.9.2 to see if it fixes everything for you? You may have to reload the VSCode window to get the activity bar icon to re-appear.

Thanks,
Benbuck

**Comment by SAbboushi** [comment]
Works fine now.  Good work
