### ISSUE TITLE
Add search history

### ISSUE THREAD

**Issue by geniosity** [bnason-nf/findallinfile#9]
I think the main feature missing from this crucial extension is the ability to see historical searches, possibly even being able to scroll up and down through the history with the arrow keys.

**Comment by bnason-nf** [comment]
Hi @geniosity,

I like this suggestion, but am having trouble thinking of a way to implement it cleanly with the [APIs](https://code.visualstudio.com/api/references/vscode-api) that VSCode currently provides. Right now I'm using showInputBox() which doesn't allow for a history-like feature. There is a showQuickPick() dialog also, but that doesn't let you type in new text. I could do something like showing the quick pick dialog if there is history, and if you pick a "Custom" field in that it could switch to the input box dialog, but that seems awkward. Any ideas?

Thanks,
Benbuck

**Comment by bnason-nf** [comment]
Hi @geniosity,

I was just experimenting, and may have been wrong about showQuickPick().

Benbuck

**Comment by bnason-nf** [comment]
For my own reference, this is documented here:

https://github.com/microsoft/vscode/issues/89601

**Comment by bnason-nf** [comment]
Hi @geniosity,

Thanks for the suggestion, I just pushed update 1.1.0 that should do what you want. Please let me know if you find any problems.

Benbuck

**Comment by geniosity** [comment]
Hi Benbuck

Thanks so much for being so quick at this, and sorry for the lack of
responses.

I've tested your latest version and it works perfectly from what I can see.

thanks!
